In [1]:
import tensorflow as tf
print(tf.__version__)

C:\Users\Administrator\anaconda3\envs\Twnsorflow-learning\Lib\site-packages\requests\__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(


2.19.0


In [9]:
# 创建第一个Tensor
scalar = tf.constant([2,7])
scalar

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 7], dtype=int32)>

In [10]:
# 检查Tensor的维数
print(scalar.ndim)

1


In [11]:
# 创建一个向量
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [12]:
# 检查Tensor vector 的向量维数
print(vector.ndim)

1


In [15]:
# 创建一个矩阵
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]],shape= (2,3))
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [16]:
# 检查向量的维数
print(matrix.ndim)

2


In [18]:
matrix2 = tf.constant([[1,2,3],
                      [2,4,6]])
print(matrix2.ndim)

2


In [20]:
another_matrix = tf.constant([[10.,7.],
                              [3.,6.],
                              [5.,8.]],dtype = tf.float16) # 指定数据类型
print(another_matrix)

tf.Tensor(
[[10.  7.]
 [ 3.  6.]
 [ 5.  8.]], shape=(3, 2), dtype=float16)


In [21]:
# 查看another_matrix的维数
print(another_matrix.ndim)

2


In [22]:
# 创建一个Tensor来增加维数
tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[7,8,9],[8,9,10]],
                      [[11,12,13],[14,15,16]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 8,  9, 10]],

       [[11, 12, 13],
        [14, 15, 16]]], dtype=int32)>

In [23]:
# 查看tensor的维数
tensor.ndim

3

In [ ]:
### 总结
# scaler:0维 表示一个数
# vector:1维 表示一个向量
# matrix:2维 表示一个矩阵
# tensor:3维 表示一个张量